sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{1\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{2\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{3\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{4\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{5\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{6\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{7\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{8\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{9\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{10\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{11\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{12\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{13\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{14\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{15\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{16\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{17\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{18\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{19\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{20\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{21\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{22\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{23\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{24\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{25\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{26\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{27\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{28\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{29\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
sed 's/\.//g;s/\(.*\)/\1/;s/\ /\n/g' rawSheilaEssay_noPunctuation.txt | sort | grep '^[0-9A-Za-z()*&:.!|,\\-]\{30\}$' | uniq -ic  | sort -rn >> outputrawSheilaEssay_noPunctuation.txt
